version: '3.7'
services:

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    networks:
      - spring-network

  api-rest:
    image: carldihe/api-rest:0.0.1-SNAPSHOT
    ports:
      - "9090:9090"
    restart: always
    networks:
      - spring-network
     
networks:
  spring-network: